name: Build and Push Docker Image

on:
  push:
    branches: feature

defaults:
  run:
    working-directory: Docker
    

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
        
      - name: build docker image
        run: |
          docker build -t mssql-bak-bacpac .
        
        
